version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    working_dir: /usr/src/app
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5010:5010'
    env_file:
      - .env
    command: sh -c "npm install && npm run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - api
    command: sh -c "npm install && npm run dev"
