version: '3.8'

services:
  api:
    image: node:20-alpine
    container_name: api
    working_dir: /usr/src/api
    volumes:
      - ../api:/usr/src/api
      - /usr/src/api/node_modules
    build:
      context: ../api
    ports:
      - "5010:5010"
    environment:
      - ENV=development
    command: npm run dev
